-- CreateTable
CREATE TABLE `TariffConfig` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `baseChargeCents` INTEGER NOT NULL DEFAULT 280,
    `kmCentsA` INTEGER NOT NULL DEFAULT 98,
    `kmCentsB` INTEGER NOT NULL DEFAULT 123,
    `kmCentsC` INTEGER NOT NULL DEFAULT 196,
    `kmCentsD` INTEGER NOT NULL DEFAULT 246,
    `waitPerHourCents` INTEGER NOT NULL DEFAULT 2940,
    `baggageFeeCents` INTEGER NOT NULL DEFAULT 200,
    `fifthPassengerCents` INTEGER NOT NULL DEFAULT 250,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
